include classpath("application.conf")

queues {
  orders-dlq {}
  orders {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "orders-dlq"
      maxReceiveCount = 5
    }
  }
}
