repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^gitops/.*/templates/
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.109.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args: [--tf-init-args=-backend=false]
      - id: terraform_tflint
        args: [--args=--config=__GIT_WORKING_DIR__/.tflint.hcl]

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.3.20
    hooks:
      - id: checkov
        args: [--config-file, .checkov.yaml]

  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: bash -c 'cd apps && go vet ./...'
        language: system
        files: ^apps/.*\.go$
        pass_filenames: false
      - id: gofmt
        name: gofmt
        entry: gofmt -l -w
        language: system
        files: \.go$
